---
name: pr-build-and-test
permissions:
  contents: read
on:
  pull_request:
    branches: ["main"]
jobs:
  pr-build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        modules:
          - hello-world
          - integers
          - iteration
          - sum
          - shapes
          - wallet
          - ./
          - di
          - countdown
          - concurrency
          - reflection
          - sync
          - context
          - numeral
          - blogposts
          - blogrenderer
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          cache: 'false'
          go-version: '1.25.2'
      - run: go build -v .
        working-directory: ${{matrix.modules}}
      - run: go test -v .
        working-directory: ${{matrix.modules}}
