---
name: pr-build-and-test
permissions:
  contents: read
on:
  pull_request:
    branches: ["main"]
jobs:
  pr-build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        modules:
          - hello-world
          - integers
          - iteration
          - sum
          - shapes
          - wallet
          - ./
          - di
          - countdown
          - concurrency
          - reflection
          - sync
          - context
          - numeral
          - blogposts
          - blogrenderer
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5  # v6.2.0
        with:
          cache: 'false'
          go-version: '1.25.6'
      - run: go build -v .
        working-directory: ${{matrix.modules}}
      - run: go test -v .
        working-directory: ${{matrix.modules}}
