---
name: pr-build-and-test
permissions:
  contents: read
on:
  pull_request:
    branches: ["main"]
jobs:
  pr-build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        modules:
          - hello-world
          - integers
          - iteration
          - sum
          - shapes
          - wallet
          - ./
          - di
          - countdown
          - concurrency
          - reflection
          - sync
          - context
          - numeral
          - blogposts
          - blogrenderer
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c  # v6.1.0
        with:
          cache: 'false'
          go-version: '1.25.4'
      - run: go build -v .
        working-directory: ${{matrix.modules}}
      - run: go test -v .
        working-directory: ${{matrix.modules}}
