---
name: Markdownlint
permissions:
  contents: read
on:
  pull_request:
  merge_group:
jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58  # v0.26.2
        with:
          fail_level: any
          filter_mode: nofilter
