---
name: Markdownlint
permissions:
  contents: read
on:
  pull_request:
  merge_group:
jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0
      - uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58  # v0.26.2
        with:
          fail_level: any
          filter_mode: nofilter
