---
name: Yamllint
permissions:
  contents: read
on:
  pull_request:
  merge_group:
jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
      - uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0  # v1.21.0
        with:
          fail_level: any
          filter_mode: nofilter
