---
name: Release Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.set-outputs.outputs.new_release }}
      tag_name: ${{ steps.set-outputs.outputs.tag_name }}
    steps:
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b  # v2.1.1
        id: app_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c  # v4.3.0
        id: rp
        with:
          release-type: go
          package-name: golang-playground
          bump-minor-pre-major: true
          token: ${{ steps.app_token.outputs.token }}

      - name: Set outputs
        id: set-outputs
        run: |
          echo "new_release=${{ steps.rp.outputs.release_created }}" >> "$GITHUB_OUTPUT"
          echo "tag_name=${{ steps.rp.outputs.tag_name }}" >> "$GITHUB_OUTPUT"

  release:
    name: Create Release
    needs: versioning
    if: ${{ needs.versioning.outputs.new_release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b  # v2.1.1
        id: app_token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ needs.versioning.outputs.tag_name }}
          token: ${{ steps.app_token.outputs.token }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: '1.25.0'

      - name: Validate Go module
        run: |
          go mod tidy
          go mod verify

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a  # v6.4.0
        with:
          distribution: goreleaser
          version: v2.9.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
